### ISSUE TITLE
Latitude 7212

### ISSUE THREAD

**Issue by anouk** [jacekkow/controlvault2-nfc-enable#4]
I am trying to get PCSC scanning working on a Latitude 7212. It has a 0a5c:5832 but the script errors/times out. 

![Screenshot from 2019-12-31 16-47-24](https://user-images.githubusercontent.com/908315/71637016-9594f700-2bee-11ea-8ccc-9d51d6b71c2c.png)

**Comment by anouk** [comment]
Tried the script on a different Latitude 7212 and it "said" it was successful PCSC_scan never recognized a card in range for contactless. It will register and contact card. 
The first 7212 has the newest 2019

**Comment by jkramarz** [comment]
Wow, what a nice tablet!

Can you provide USBPcap dumps from Windows?

**Comment by anouk** [comment]
pcsc_scan detects the contactless reader but the antenna is never turned on. (I have a fancy 14443A pcb card that lights up a led when powered) 

some what same thin in windows 

the "NFC proximity provider" works like a charm but not PC/SC

 if i disable  "NFC proximity provider" in windows the card stops getting power 

i need to reload windows and I will also load  USBPcap dumps from Windows

**Comment by anouk** [comment]
Ok... I think I have a better "theory" of what is going on. 
after looking into the spec sheet of the Broadcom NFC Chip BCM20795. I think it is set to route certain types of cards to proximity and others to PC/SC.  I found that if I hold a NFC credit card up it routes to PC/SC but all 14443A card are getting routed only to Proximity provider. 

There is a tool in the dell driver called "setcardsrouting.exe" 

it appears to allow me to change toe routing of some kinds of cards but unfortunatley (I can change my credit card via the -isoarfid flag back and forward) so that somthing
That said, I have about 25 thousand Mifare ultralight (ISO1443-3A) cards deployed and no matter what I change they always route to NFC proximity provider.

**Comment by jacekkow** [comment]
@anouk: Are you trying to read Mifare Ultralight using PC/SC? That won't work as these are completely different protocols! PC/SC is APDU-based protocol (that for contactless cards it uses ISO 14443, part 4), while Mifare only uses radio interface (ISO 14443, part 2) and anticollision systems from that standard (ISO 14443, part 3). The exception is Mifare DESFire, but that's another story.
What you need is libnfc interface (or some other low level one) to the Broadcom reader - a port of https://android.googlesource.com/platform/external/libnfc-nci/ to standard kernel with Dell-specific changes or something in that realm.
If you want to enable reading compliant ISO 14443-4 cards on Linux, we might be able to help you. Unfortunately as for the libnfc-nci, you are on your own :(
