### ISSUE TITLE
Add support for 0a5c:5843

### ISSUE THREAD

**Issue by Any0ne22** [jacekkow/controlvault2-nfc-enable#9]
I have a 0a5c:5843 NFC readr on my Dell Latitude 5501 but I'm not able to use it on Ubuntu 20.04, could you add support for this chip?

**Comment by jacekkow** [comment]
This is a different hardware (ControlVault3) that I have no access to, unfortunately.

If you could sniff communication between Windows and the device using USBPcap:
https://desowin.org/usbpcap/tour.html
then I might be able to come up with something (skip the part about detaching device).

When you have sniffing enabled go to Device Manager, find ControlVault NFC device, select Disable command, wait a moment and reenable the device.

You can attach the resulting .pcap file to this issue (optionally encrypting it with my public GPG key) or send it to me privately.

**Comment by lgarbarini** [comment]
@jacekkow I have pcaps from `0a5c:5843` on a Dell Latitude 7400. I can't seem to track down your contact info/gpg key, but am happy to pass along the pcaps when I do.

**Comment by jacekkow** [comment]
@lgarbarini 
GitHub posts my GPG key at: https://api.github.com/users/jacekkow/gpg_keys

I'm also attaching it for convenience:
[gpg.txt](https://github.com/jacekkow/controlvault2-nfc-enable/files/4920251/gpg.txt)

**Comment by lgarbarini** [comment]
Thank you, pcaps are on their way

**Comment by jacekkow** [comment]
I finally found some time to look at these dumps. These are not as scary as I have thought - general framework looks the same, only commands differ:
https://gist.github.com/jacekkow/8acf2bbc164dc377df9913a47807d589

I'll try to wrap it up during the weekend somehow.

**Comment by jacekkow** [comment]
Could you try:
https://github.com/jacekkow/controlvault2-nfc-enable/tree/cv3
(branch cv3)?

Usage changed slightly:
```
./nfc.py on
```
or
```
sudo ./nfc.py on
```

**Comment by Any0ne22** [comment]
I tried on my Latitude 5501 with `0a5c:5843` and I keep getting this error
```python
INFO:__main__:Looking for supported device...
Traceback (most recent call last):
  File "./nfc.py", line 62, in <module>
    handler = UsbDeviceFinder.find()
  File "./nfc.py", line 46, in find
    raise Exception('Cannot find BCM device - check list of supported devices')
Exception: Cannot find BCM device - check list of supported devices
```

PS: sorry if I didn't send the pcap you asked for, I was really busy during the past month

**Comment by jacekkow** [comment]
My mistake - I have added `0a5c:5833` instead of `0a5c:5843`.
Fixed on that branch (note that I have made amend to the existing commit instead of a new one).

**Comment by Any0ne22** [comment]
This time, I got this error:
```python
NFO:__main__:Looking for supported device...
INFO:__main__:Found 0A5C:5843
DEBUG:cvcomm:Enumerating interfaces...
Traceback (most recent call last):
  File "./nfc.py", line 62, in <module>
    handler = UsbDeviceFinder.find()
  File "./nfc.py", line 49, in find
    handler = cls._cls_matcher(device)
  File "./nfc.py", line 36, in _cls_matcher
    return matcher.handler(device)
  File "./nfc.py", line 22, in <lambda>
    UsbDeviceMatcher({'idVendor': 0x0A5C, 'idProduct': 0x5843}, lambda device: __import__('cv3').ControlVault3(device)),
  File "/home/tom/Téléchargements/controlvault2-nfc-enable-cv3/cv3.py", line 26, in __init__
    self.communicator = cvcomm.ControlVaultCommunicator(device)
  File "/home/tom/Téléchargements/controlvault2-nfc-enable-cv3/cvcomm.py", line 13, in __init__
    self.bulk_in, self.bulk_out = self._find_endpoints()
  File "/home/tom/Téléchargements/controlvault2-nfc-enable-cv3/cvcomm.py", line 68, in _find_endpoints
    raise Exception('Cannot find vendor-specific interface')
Exception: Cannot find vendor-specific interface
```

**Comment by jacekkow** [comment]
This is a part I have not touched - `iInterface` value is different. I have just pushed another update.

**Comment by Any0ne22** [comment]
It works! Thank you very much for this!

**Comment by jacekkow** [comment]
There is probably some room for improvements, but I'll leave it for when I get my hands on some laptop with that chip.

Great it works, I'll push these changes to master branch.
